### ISSUE TITLE
ModuleNotFoundError: No module named 'macad_gym.envs.intersection.stop_sign_urban_intersection_3c'

### ISSUE THREAD

**Issue by rsuwa** [praveen-palanisamy/macad-agents#1]
Hi, @praveen-palanisamy.
I want to use your code but an error has occurred in my situation. :cry:
So I want your help.

I'm sorry for my poor English. :bow:

## Reproduction

Run:
```bash
docker run --gpus all -it -e CARLA_SERVER=/software/CarlaUE4.sh -v ${HOME}/src/github.com/praveen-palanisamy/macad-agents:/macad-agents -w /macad-agents/src macad-agents:latest python -m macad_agents.rllib.impala_multiagent_shared_weights.py

```

Then, this error has occurred:

```bash
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/opt/conda/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/macad-agents/src/macad_agents/rllib/impala_multiagent_shared_weights.py", line 15, in <module>
    from macad_gym.envs.intersection.stop_sign_urban_intersection_3c import \
ModuleNotFoundError: No module named 'macad_gym.envs.intersection.stop_sign_urban_intersection_3c'
Killing live carla processes set()
```

## Environment

- OS: Ubuntu 18.04.3 LTS
- Docker: 19.03.5
- CPU: AMD Ryzen 5 3600X 6-Core Processor
- GPU: GeForce RTX 2070 (Driver Version: 430.50)

**Comment by praveen-palanisamy** [comment]
Hi @rsuwa : Thanks for reporting this issue!
The code was using an older MACAD-Gym API. I pushed an update in 7837b34 which should use the latest and OpenAI Gym-compatible API for the MACAD-Gym environments.

Please try again and post back. I will leave this open for sometime to get your feedback.

**Comment by rsuwa** [comment]
@praveen-palanisamy 
Thank you for update in <https://github.com/praveen-palanisamy/macad-agents/commit/7837b3424a7af9ae48ff12b6234c1e5de97297e8>.

However, another error occuerrd;

## Error
```bash
Error during reset: Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/macad_gym/carla/multi_env.py", line 552, in reset
    self._init_server()
  File "/opt/conda/lib/python3.6/site-packages/macad_gym/carla/multi_env.py", line 482, in _init_server
    carla.Rotation(yaw=180 + angle, pitch=-15)))
RuntimeError: trying to access an expired episode; a new episode was started in the simulation but an object tried accessing the old one.

```

## Debug log
```bash
DEBUG:ray.worker:Suppressing error from worker: [36mray_worker[39m (pid=48, host=09f5e10c76e5)
  File "/opt/conda/lib/python3.6/site-packages/ray/rllib/agents/agent.py", line 248, in __init__
    Trainable.__init__(self, config, logger_creator)
  File "/opt/conda/lib/python3.6/site-packages/ray/tune/trainable.py", line 88, in __init__
    self._setup(copy.deepcopy(self.config))
  File "/opt/conda/lib/python3.6/site-packages/ray/rllib/agents/agent.py", line 318, in _setup
    self._init()
  File "/opt/conda/lib/python3.6/site-packages/ray/rllib/agents/ppo/ppo.py", line 75, in _init
    self.env_creator, self._policy_graph)
  File "/opt/conda/lib/python3.6/site-packages/ray/rllib/agents/agent.py", line 438, in make_local_evaluator
    config["local_evaluator_tf_session_args"]
  File "/opt/conda/lib/python3.6/site-packages/ray/rllib/agents/agent.py", line 578, in _make_evaluator
    output_creator=output_creator)
  File "/opt/conda/lib/python3.6/site-packages/ray/rllib/evaluation/policy_evaluator.py", line 292, in __init__
    self.env, make_env=make_env, num_envs=num_envs)
  File "/opt/conda/lib/python3.6/site-packages/ray/rllib/env/async_vector_env.py", line 73, in wrap_async
    make_env=make_env, existing_envs=[env], num_envs=num_envs)
  File "/opt/conda/lib/python3.6/site-packages/ray/rllib/env/async_vector_env.py", line 283, in __init__
    self.env_states = [_MultiAgentEnvState(env) for env in self.envs]
  File "/opt/conda/lib/python3.6/site-packages/ray/rllib/env/async_vector_env.py", line 283, in <listcomp>
    self.env_states = [_MultiAgentEnvState(env) for env in self.envs]
  File "/opt/conda/lib/python3.6/site-packages/ray/rllib/env/async_vector_env.py", line 327, in __init__
    self.reset()
  File "/opt/conda/lib/python3.6/site-packages/ray/rllib/env/async_vector_env.py", line 345, in reset
    self.last_obs = self.env.reset()
  File "/opt/conda/lib/python3.6/site-packages/macad_gym/carla/multi_env.py", line 560, in reset
    raise error
  File "/opt/conda/lib/python3.6/site-packages/macad_gym/carla/multi_env.py", line 552, in reset
    self._init_server()
  File "/opt/conda/lib/python3.6/site-packages/macad_gym/carla/multi_env.py", line 482, in _init_server
    carla.Rotation(yaw=180 + angle, pitch=-15)))
RuntimeError: trying to access an expired episode; a new episode was started in the simulation but an object tried accessing the old one.
```

**Comment by praveen-palanisamy** [comment]
Did the training process stop at that error? It looks like an intermittent state where a new episode was already started before completing `env.reset()`. Such issues with CARLA [has been reported before](https://github.com/carla-simulator/carla/issues/1817). In MACAD-Agents (ray), when that happens, that episode is discarded and a new env instances is spawned by ray's trial runner and the training should continue.

**Comment by rsuwa** [comment]
This is the last error that was displayed after ray's several trial.

```bash
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/macad-agents/src/macad_agents/rllib/ppo_multiagent_shared_weights.py", line 145, in <module>
    "checkpoint_at_end": True,
  File "/opt/conda/lib/python3.6/site-packages/ray/tune/tune.py", line 185, in run_experiments
    raise TuneError("Trials did not complete", errored_trials)
ray.tune.error.TuneError: ('Trials did not complete', [PPO_HomoNcomIndePOIntrxMASS3CTWN3-v0_0])
Killing live carla processes set()

```

Hmm, 
I have noticed a large number of permission errors.
Does this error help?
 
[`/ray_results/MA-PPO-SSUI3CCARLA/PPO_HomoNcomIndePOIntrxMASS3CTWN3-v0_0_2019-12-24_16-04-05k28fogtx/logs/server_33813.log`](https://github.com/praveen-palanisamy/macad-agents/files/3998455/server_33813.log)

**Comment by tbienhoff** [comment]
I am running into the same issues as @rsuwa.

Have these problems been resolved?

**Comment by praveen-palanisamy** [comment]
Hi @tbienhoff :
Did you say you are getting the following error?
> ModuleNotFoundError: No module named 'macad_gym.envs.intersection.stop_sign_urban_intersection_3c'

This is fixed in the master branch as reported above.

Or did you run into the following runtime error from CARLA?
>RuntimeError: trying to access an expired episode; a new episode was started in the simulation but an object tried accessing the old one

If the latter is the case, please state the CARLA version you are using. The error seems to stem from an incompatible CARLA server binary version. The incompatibility may arise if you are using different versions of CARLA server and python client library versions.
Successful multi-agent policies were trained using the code and the instructions in the [README](https://github.com/praveen-palanisamy/macad-agents) with CARLA version (https://github.com/praveen-palanisamy/macad-agents) 0.9.4 and 0.9.5 x.

**Comment by tbienhoff** [comment]
I am running into the second error trying to access an expired episode.

I followed the README instructions to build a docker image but it appears the CARLA server version is 0.9.4, but the client version is 0.9.5.

I will change the Docker image to use 0.9.5 to see if that fixes the error.

**Comment by praveen-palanisamy** [comment]
Closing this issue since a resolution was proposed. Re-open if further investigation is necessary.
