### ISSUE TITLE
How to run it without using docker?

### ISSUE THREAD

**Issue by SHITIANYU-hue** [praveen-palanisamy/macad-agents#2]
How to run it without using docker?

**Comment by praveen-palanisamy** [comment]
Hi @SHITIANYU-hue , 

If you have all the necessary dependencies installed an configured on your host machine, you can run the agent script like shown below:
`cd macad-agents/src && python -m macad_agents.rllib.ppo_multiagent_shared_weights`

A brief gist of what you need to setup on your host machine is listed below:
https://github.com/praveen-palanisamy/macad-agents/blob/5e0bf86e4175ffd3aabf52ac32016d4050da9cff/run.sh#L8-L12

Where `-e` is equivalent to `export` using the `bash` terminal.

**Comment by praveen-palanisamy** [comment]
@SHITIANYU-hue ,
Glad that you are now able to run it without using the docker container (?). 

Did you modify the [`macad_agents/rllib/ppo_multiagent_shared_weights.py`](https://github.com/praveen-palanisamy/macad-agents/blob/master/src/macad_agents/rllib/ppo_multiagent_shared_weights.py) script or the environment code to change the observation/input space?

The error `ValueError: Unexpected input shape (468, 468, 3), expected (84, 84, 3)` seems to indicate that the observations/inputs are not the expected value of `(84, 84, 3)`. By default the agent script and the env script will use `(84, 84, x3)` as the observation space.

**Comment by SHITIANYU-hue** [comment]
Yes, I also think that should use 84, but I didn't modify the code actually.

**Comment by SHITIANYU-hue** [comment]
Hello, I tried to rebuild the code from this repository, but I still meet this error:

ValueError: Unexpected input shape (168, 168, 3), expected (84, 84, 3), value = [[[-0.171875  -0.1015625  0.046875 ]

Then, I changed the observation space 84 to 168, dim:84 to 168. But there will be a memory problem:
Traceback (most recent call last):
  File "/home/tianyushi/miniconda3/envs/macad-gym/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 378, in _process_events
    result = self.trial_executor.fetch_result(trial)
  File "/home/tianyushi/miniconda3/envs/macad-gym/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 228, in fetch_result
    result = ray.get(trial_future[0])
  File "/home/tianyushi/miniconda3/envs/macad-gym/lib/python3.6/site-packages/ray/worker.py", line 2211, in get
    raise value
ray.worker.RayTaskError: ^[[36mray_PPOAgent:train()^[[39m (pid=4429, host=153SMART-08-ULTS)
  File "/home/tianyushi/miniconda3/envs/macad-gym/lib/python3.6/site-packages/ray/memory_monitor.py", line 78, in raise_if_low_memory
    self.error_threshold))
ray.memory_monitor.RayOutOfMemoryError: More than 95% of the memory on node 153SMART-08-ULTS is used (16.36 / 16.6 GB). The top 5 memory consumers are:

PID     MEM     COMMAND
6013    2.01GB  /home/tianyushi/software/CARLA_0.9.4/CarlaUE4/Binaries/Linux/CarlaUE4 CarlaUE4 /Game/Carla/Maps/Town
4429    2.01GB  ray_PPOAgent:train()
5995    1.92GB  /home/tianyushi/software/CARLA_0.9.4/CarlaUE4/Binaries/Linux/CarlaUE4 CarlaUE4 /Game/Carla/Maps/Town
21347   1.47GB  /home/tianyushi/software/pycharm-community-2019.3.2/jbr/bin/java -classpath /home/tianyushi/software
4431    0.88GB  ray_PolicyEvaluator

In addition, ~1.58 GB of shared memory is currently being used by the Ray object store. You can set the object store size with the `object_store_memory` parameter when starting Ray, and the max Redis size with `redis_max_memory`.

I think the reason that adjusts the larger space into 84 maybe is to save memory. But how to solve the problem of the observation space dimension?

**Comment by praveen-palanisamy** [comment]
Hello @SHITIANYU-hue,

The shape: `(168, 168, 3)` is puzzling because it is not set anywhere in the code. I suspect it to be a local config change.
I tried to reproduce your state by running it from a clean clone of [MACAD-Agents](https://github.com/praveen-palanisamy/macad-agents/) and I see no such errors.
Following is the portion of the log that confirms that all the agent (`car1`, `car2`, `car3`) observations (inputs) are of shape : `(84, 84, 3)`:

```bash
2020-08-25 09:55:07,175 DEBUG tf_policy_graph.py:149 -- Created <ray.rllib.agents.ppo.ppo_policy_graph.PPOPolicyGraph object at 0x7fb10fb22cf8> with loss inputs: {'obs': <tf.Tensor 'car1/obs:0' shape=(?, 84, 84, 3) dtype=float32>, 'value_targets': <tf.Tensor 'car1/value_targets:0' shape=(?,) dtype=float32>, 'advantages': <tf.Tensor 'car1/advantages:0' shape=(?,) dtype=float32>, 'actions': <tf.Tensor 'car1/action:0' shape=(?,) dtype=int64>, 'logits': <tf.Tensor 'car1/logits:0' shape=(?, 9) dtype=float32>, 'vf_preds': <tf.Tensor 'car1/vf_preds:0' shape=(?,) dtype=float32>, 'prev_actions': <tf.Tensor 'car1/action_1:0' shape=(?,) dtype=int64>, 'prev_rewards': <tf.Tensor 'car1/prev_reward:0' shape=(?,) dtype=float32>}
2020-08-25 09:55:07,559 INFO catalog.py:308 -- Using custom preprocessor sq_im_84
2020-08-25 09:55:07,560 DEBUG catalog.py:316 -- Created preprocessor <__main__.ImagePreproc object at 0x7fb1bc483630>: Box(84, 84, 3) -> (84, 84, 3)
2020-08-25 09:55:07,572 DEBUG catalog.py:215 -- Using custom model mnih15_shared_weights
2020-08-25 09:55:07,664 DEBUG catalog.py:205 -- Created model <macad_agents.rllib.models.Mnih15SharedWeights object at 0x7fb1bc305e48>: ({'obs': <tf.Tensor 'car2/obs:0' shape=(?, 84, 84, 3) dtype=float32>, 'prev_actions': <tf.Tensor 'car2/action_1:0' shape=(?,) dtype=int64>, 'prev_rewards': <tf.Tensor 'car2/prev_reward:0' shape=(?,) dtype=float32>, 'is_training': <tf.Tensor 'car2/PlaceholderWithDefault:0' shape=() dtype=bool>} of Box(84, 84, 3), None, None) -> Tensor("car2/mnih15_FC/fully_connected/BiasAdd:0", shape=(?, 9), dtype=float32), []
2020-08-25 09:55:07,671 DEBUG catalog.py:215 -- Using custom model mnih15_shared_weights
2020-08-25 09:55:07,761 DEBUG catalog.py:205 -- Created model <macad_agents.rllib.models.Mnih15SharedWeights object at 0x7fb1bc31f630>: ({'obs': <tf.Tensor 'car2/obs:0' shape=(?, 84, 84, 3) dtype=float32>, 'prev_actions': <tf.Tensor 'car2/action_1:0' shape=(?,) dtype=int64>, 'prev_rewards': <tf.Tensor 'car2/prev_reward:0' shape=(?,) dtype=float32>, 'is_training': <tf.Tensor 'car2/PlaceholderWithDefault:0' shape=() dtype=bool>} of Box(84, 84, 3), None, None) -> Tensor("car2/value_function/mnih15_FC/fully_connected/BiasAdd:0", shape=(?, 1), dtype=float32), []
2020-08-25 09:55:08,824 DEBUG tf_policy_graph.py:149 -- Created <ray.rllib.agents.ppo.ppo_policy_graph.PPOPolicyGraph object at 0x7fb1bc305b38> with loss inputs: {'obs': <tf.Tensor 'car2/obs:0' shape=(?, 84, 84, 3) dtype=float32>, 'value_targets': <tf.Tensor 'car2/value_targets:0' shape=(?,) dtype=float32>, 'advantages': <tf.Tensor 'car2/advantages:0' shape=(?,) dtype=float32>, 'actions': <tf.Tensor 'car2/action:0' shape=(?,) dtype=int64>, 'logits': <tf.Tensor 'car2/logits:0' shape=(?, 9) dtype=float32>, 'vf_preds': <tf.Tensor 'car2/vf_preds:0' shape=(?,) dtype=float32>, 'prev_actions': <tf.Tensor 'car2/action_1:0' shape=(?,) dtype=int64>, 'prev_rewards': <tf.Tensor 'car2/prev_reward:0' shape=(?,) dtype=float32>}
2020-08-25 09:55:09,186 INFO catalog.py:308 -- Using custom preprocessor sq_im_84
2020-08-25 09:55:09,187 DEBUG catalog.py:316 -- Created preprocessor <__main__.ImagePreproc object at 0x7fb1bc05b6d8>: Box(84, 84, 3) -> (84, 84, 3)
2020-08-25 09:55:09,194 DEBUG catalog.py:215 -- Using custom model mnih15_shared_weights
2020-08-25 09:55:09,301 DEBUG catalog.py:205 -- Created model <macad_agents.rllib.models.Mnih15SharedWeights object at 0x7fb10c1baeb8>: ({'obs': <tf.Tensor 'car3/obs:0' shape=(?, 84, 84, 3) dtype=float32>, 'prev_actions': <tf.Tensor 'car3/action_1:0' shape=(?,) dtype=int64>, 'prev_rewards': <tf.Tensor 'car3/prev_reward:0' shape=(?,) dtype=float32>, 'is_training': <tf.Tensor 'car3/PlaceholderWithDefault:0' shape=() dtype=bool>} of Box(84, 84, 3), None, None) -> Tensor("car3/mnih15_FC/fully_connected/BiasAdd:0", shape=(?, 9), dtype=float32), []
```

Also, note that if you customized [`ppo_multiagent_shared_weights`](https://github.com/praveen-palanisamy/macad-agents/blob/master/src/macad_agents/rllib/ppo_multiagent_shared_weights.py) by changing the `"model"` configuration or the `"custom_preprocessor"`, you will have to make sure the dimensions match which otherwise can lead to the error you observed.

If you can do a clean checkout or clone of this repo and try again, it will help to know what's causing the error on your side.

Also, please attach the complete log (as a file attachment or as formatted text) next time so that we can identify what's going wrong.

**Comment by SHITIANYU-hue** [comment]
[error_2020-08-25_18-54-37.txt](https://github.com/praveen-palanisamy/macad-agents/files/5126673/error_2020-08-25_18-54-37.txt)

**Comment by SHITIANYU-hue** [comment]
> [error_2020-08-25_18-54-37.txt](https://github.com/praveen-palanisamy/macad-agents/files/5126673/error_2020-08-25_18-54-37.txt)

Hi @praveen-palanisamy , i have double checked the code and run it with a clean repo again, but i still find this dimension error. Actually, i have also tried such as impala_agent_independent. I also find the same bug. Hope you could help me.

**Comment by SHITIANYU-hue** [comment]
May I ask you what version of macad-gym did you use for this macad-agent? Is it the latest one?https://github.com/praveen-palanisamy/macad-gym/releases/tag/v0.1.3

**Comment by praveen-palanisamy** [comment]
In the error log that you provided, the stack only has trace from the RLLib library invocation and nothing from the MACAD-Agents (or MACAD-Agents). Could you get a full trace from your side? That'll help to locate what is causing this issue on your end. It may be just that the pre-processing steps for the observations aren't getting applied for an unknown reason.

Yes. The latest version (v0.1.3) of MACAD-Gym obtained from PyPi through: `pip install -U macad-gym` was tested to work with the latest HEAD on MACAD-Agents.

**Comment by SHITIANYU-hue** [comment]
Hi @praveen-palanisamy , i find out why it will occur this error. In this code `  "actors": {
                "car1": {
                    "type": "vehicle_4W",
                    "enable_planner": True,
                    "convert_images_to_video": False,
                    "early_terminate_on_collision": True,
                    "reward_function": "corl2017",
                    "scenarios": "SSUI3C_TOWN3_CAR1",
                    "manual_control": False,
                    "auto_control": False,
                    "camera_type": "rgb",
                    "collision_sensor": "on",
                    "lane_sensor": "on",
                    "log_images": False,
                    "log_measurements": False,
                    "render": True,
                    "x_res": 168,
                    "y_res": 168,
                    "use_depth_camera": False,
                    "send_measurements": False,
                },`  
the x_res and y_res are **168**, but in this code:
[https://github.com/praveen-palanisamy/macad-agents/blob/master/src/macad_agents/rllib/ppo_multiagent_shared_weights.py](url). The observation space is **84**: `obs_space = Box(0.0, 255.0, shape=(84, 84, 3))`

I changed the **obs_space,   "custom_preprocessor": "sq_im_84", "dim": 84,** to fit the 168.  Then it doesn't have this problem. 

However, according to my understanding, this line of code `ModelCatalog.register_custom_preprocessor("sq_im_84", ImagePreproc)` should be able to transform this input 168 to 84, but i don't know why it doesn't function well.
