### ISSUE TITLE
Ray error when running continuous A3C

### ISSUE THREAD

**Issue by SHITIANYU-hue** [praveen-palanisamy/macad-agents#9]
Hello,

when I run:

` python -m macad_agents.a3c.continuous_A3C_tune`.

I found that there will be the following error:
Traceback (most recent call last):
  File "/home/tianyushi/miniconda3/envs/macad-gym/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/tianyushi/miniconda3/envs/macad-gym/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/tianyushi/code/macad-agents/src/macad_agents/a3c/continuous_A3C_tune.py", line 74, in <module>
    "UPDATE_GLOBAL_ITER": 5,
  File "/home/tianyushi/miniconda3/envs/macad-gym/lib/python3.6/site-packages/ray/tune/tune.py", line 185, in run_experiments
    raise TuneError("Trials did not complete", errored_trials)
ray.tune.error.TuneError: ('Trials did not complete', [continuous_A3C_carla_env_0])
Killing live carla processes set()

and the log file is :
[error_2020-08-27_16-06-25.txt](https://github.com/praveen-palanisamy/macad-agents/files/5139055/error_2020-08-27_16-06-25.txt)

**Comment by praveen-palanisamy** [comment]
I assume this is fixed with your PR #8. Please re-open if an issue still exists.
